config/routes.rb
Selectcom::Application.routes.draw do
  # get "admins/new"
  # get "dashboard/index"

  root 'dashboard#index'
  resources :jobs
  resources :clients
  resources :sessions
  resources :teches
  resources :admins
  resources :sale_orders
  resources :attaches
  resources :tech_jobs
  resources :notes
  
  match '/signin',      to: 'sessions#new',           via: 'get'
  match '/signout',     to: 'sessions#destroy',       via: 'delete'
  match '/new_job',    to: 'jobs#new',               via: 'delete'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
	has_one :user

	accepts_nested_attributes_for :user
	
	has_attached_file :photo, style: { :medium => "400x300>", :thumb => "100x100>" }
	validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }
end

app/models/attach.rb
class Attach < ActiveRecord::Base
	belongs_to :job
	mount_uploader :document, DocumentUploader
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many 	:locations, :dependent => :destroy
	has_many 	:site_contacts, :dependent => :destroy
	has_many 	:client_reps, :dependent => :destroy
	has_many    :jobs, :dependent => :destroy
	has_one     :user, :dependent => :destroy

	accepts_nested_attributes_for :locations, :allow_destroy => true
	accepts_nested_attributes_for :site_contacts, :allow_destroy => true
	accepts_nested_attributes_for :client_reps, :allow_destroy => true
	accepts_nested_attributes_for :jobs, :allow_destroy => true
	accepts_nested_attributes_for :user, :allow_destroy => true

	validates :name, presence: true
	validates :phone, presence: true
end

app/models/client_rep.rb
class ClientRep < ActiveRecord::Base
	belongs_to :client
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :client
	has_one :sale_order
	has_many :attaches
	has_many :tech_jobs
	has_many :notes

	# validates :client_id, presence: true
	accepts_nested_attributes_for :sale_order
	accepts_nested_attributes_for :attaches
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :client
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
	belongs_to :job
end

app/models/sale_order.rb
class SaleOrder < ActiveRecord::Base
	belongs_to :job
	# before_save { self.sales_order = sales_order.downcase }
	validates :sales_order, presence: true, uniqueness: { case_sensitive: false }
	# validates :job_id, presence: true
	
end

app/models/site_contact.rb
class SiteContact < ActiveRecord::Base
	belongs_to :client
end

app/models/tech.rb
class Tech < ActiveRecord::Base
	has_one :user
	has_many :tech_jobs

	accepts_nested_attributes_for :user
	
	has_attached_file :photo, style: { :medium => "400x300>", :thumb => "100x100>" }
	# validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }

end

app/models/tech_job.rb
class TechJob < ActiveRecord::Base
	belongs_to :job
	belongs_to :tech

	validates_uniqueness_of :job_id, :scope => :tech_id, :message => "can only have one tech assigned"
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :client
	belongs_to :tech
	belongs_to :admin
	has_many   :notes
	
	has_secure_password

	before_save { self.email = email.downcase }
	before_create :create_remember_token

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	# validates :username, presence: true, length: { minimum: 4 }, uniqueness: { case_sensitive: false }	
	validates :password, length: { minimum: 6 }

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private 
		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/teches_controller.rb
class TechesController < ApplicationController
	before_action :set_tech, only: [:edit, :update]

	def index
		@teches = Tech.paginate(page:params[:page])
  	end

	def new
		@tech = Tech.new
		@tech.build_user unless @tech.user
	end

	def create
		@tech = Tech.new(tech_params)
		if @tech.save
			flash[:success] = "Tech added successfully"
			redirect_to teches_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update 
		if @tech.update(tech_params)
	 		flash[:success] = "Tech updated successfully"
	 		redirect_to teches_path
	 	else
	 		render 'edit'
	 	end 	
	end

	private 
	  	def set_tech
	  		@tech = Tech.find(params[:id])
	  	end

	  	def tech_params
	  		params.require(:tech).permit(
	  			:first_name, :last_name, :contact, :city, :photo, :start_date,
	  			user_attributes: [
					:id,
					:email,
					:password,
					:password_confirmation,
					:role
				]
	  		)
	  	end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/attaches_helper.rb
module AttachesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
    	user == current_user
  	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
	end

	def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end
end

app/helpers/tech_jobs_helper.rb
module TechJobsHelper
end

app/helpers/teches_helper.rb
module TechesHelper
end

app/helpers/techs_helper.rb
module TechsHelper
end

app/views/teches/_tech.html.erb
<tr>
	<td><%= tech.first_name %></td>
	<td><%= tech.last_name %></td>
	<td><%= tech.city %></td>
	<td><%= tech.contact %></td>
	<td><%=  %></td>
	<td></td>
	<td></td>
	<td>
		<%= link_to(edit_tech_path(tech)) do %>
			<i class="glyphicon glyphicon-pencil"></i>
		<% end %>
	</td>
</tr>

app/views/teches/_tech_field.html.erb
<div id="tech" class="row row-content">
	<div class='col-xs-6'>
		<div class='form-group'>
		    <%= f.label :first_name, 'First Name', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :first_name, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :last_name, 'Last Name', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :last_name, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :contact, 'Contact', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :contact, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :city, 'City', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :city, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :photo, 'Photo', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.file_field :photo, class: 'form-control' %>
		    </div>
		</div><br>

		<div class="form-group">
          <%= f.label :start_date, 'Start Date', class: 'control-label col-xs-3' %>
          <div class="col-lg-8">
            <%= f.date_field :start_date, class: 'form-control' %>
          </div>
        </div>

	</div>

	<div class='col-xs-6'>
		<div class='form-group'>
		    <%= f.label :address, 'Address', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_area :address, rows: 8, cols: 100,  class: 'form-control' %>
		    </div>
		</div><br>
		
	</div>
</div>

app/views/teches/edit.html.erb
<%= form_for(@tech, class: 'form-horizontal') do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="row row-content" style="padding-bottom: 7px;">
		<div class="col-xs-2">
			<%= image_tag(@tech.photo) %>
		</div>
		<div class="col-xs-2">
			<h4>Start Date</h4>
			<%= f.date_field :start_date, class: 'start_date' %>
		</div>
	</div>
	<div class="row lg-bg-white">
		<br>
			<%= render 'tech_field', f: f %>

			<%= f.fields_for :user do |l| %>
			  	<%= l.hidden_field :tech_id, value: @tech.id %>
				<%= l.hidden_field :role, value: 'tech' %>
			  	<%= render 'shared/user_field', f: l %>
			<% end %>
		  	<div style="margin-left: 10px;"><%= f.submit "Save", class: "btn lg-button" %></div>
		
		<br>
	</div>
<% end %> 	

app/views/teches/index.html.erb
<div class="row row-content" style="padding-bottom: 7px;">
	<div class="pull-right">
		<%= link_to 'Add Tech', new_tech_path, class: 'btn lg-button' %>
	</div>
</div>
<div class="row lg-bg-white">
	<table class="table">
		<tr>
			<th>FIRST NAME</th>
			<th>LAST NAME</th>
			<th>CITY</th>
			<th>CONTACT</th>
			<th>EMAIL</th>
			<th>LAST 30 DAYS</th>
			<th>OPEN JOBS</th>
			<th>ACTION</th>
		</tr>
		<%= render @teches %>
	</table>


</div>

app/views/teches/new.html.erb
<div class="row lg-bg-white">
	<br>
	<%= form_for(@tech, class: 'form-horizontal') do |f| %>
	  	<%= render 'shared/error_messages', object: f.object %>

		<%= render 'tech_field', f: f %>

		<%= f.fields_for :user do |l| %>
		  	<%= l.hidden_field :tech_id, value: @tech.id %>
			<%= l.hidden_field :role, value: 'tech' %>
		  	<%= render 'shared/user_field', f: l %>
		<% end %>
	  	<div style="margin-left: 10px;"><%= f.submit "Save", class: "btn lg-button" %></div>
	<% end %> 	
	<br>
</div>