config/routes.rb
Selectcom::Application.routes.draw do
  # get "admins/new"
  # get "dashboard/index"

  root 'dashboard#index'
  resources :jobs
  resources :clients
  resources :sessions
  resources :teches
  resources :admins
  resources :sale_orders
  resources :attaches
  resources :tech_jobs
  resources :notes
  
  match '/signin',      to: 'sessions#new',           via: 'get'
  match '/signout',     to: 'sessions#destroy',       via: 'delete'
  match '/new_job',    to: 'jobs#new',               via: 'delete'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
	has_one :user

	accepts_nested_attributes_for :user
	
	has_attached_file :photo, style: { :medium => "400x300>", :thumb => "100x100>" }
	validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }
end

app/models/attach.rb
class Attach < ActiveRecord::Base
	belongs_to :job
	mount_uploader :document, DocumentUploader
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many 	:locations, :dependent => :destroy
	has_many 	:site_contacts, :dependent => :destroy
	has_many 	:client_reps, :dependent => :destroy
	has_many    :jobs, :dependent => :destroy
	has_one     :user, :dependent => :destroy

	accepts_nested_attributes_for :locations, :allow_destroy => true
	accepts_nested_attributes_for :site_contacts, :allow_destroy => true
	accepts_nested_attributes_for :client_reps, :allow_destroy => true
	accepts_nested_attributes_for :jobs, :allow_destroy => true
	accepts_nested_attributes_for :user, :allow_destroy => true

	validates :name, presence: true
	validates :phone, presence: true
end

app/models/client_rep.rb
class ClientRep < ActiveRecord::Base
	belongs_to :client
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :client
	has_one :sale_order
	has_many :attaches
	has_many :tech_jobs
	has_many :notes

	# validates :client_id, presence: true
	accepts_nested_attributes_for :sale_order
	accepts_nested_attributes_for :attaches
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :client
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
	belongs_to :job
end

app/models/sale_order.rb
class SaleOrder < ActiveRecord::Base
	belongs_to :job
	# before_save { self.sales_order = sales_order.downcase }
	validates :sales_order, presence: true, uniqueness: { case_sensitive: false }
	# validates :job_id, presence: true
	
end

app/models/site_contact.rb
class SiteContact < ActiveRecord::Base
	belongs_to :client
end

app/models/tech.rb
class Tech < ActiveRecord::Base
	has_one :user
	has_many :tech_jobs

	accepts_nested_attributes_for :user
	
	has_attached_file :photo, style: { :medium => "400x300>", :thumb => "100x100>" }
	# validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }

end

app/models/tech_job.rb
class TechJob < ActiveRecord::Base
	belongs_to :job
	belongs_to :tech

	validates_uniqueness_of :job_id, :scope => :tech_id, :message => "can only have one tech assigned"
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :client
	belongs_to :tech
	belongs_to :admin
	has_many   :notes
	
	has_secure_password

	before_save { self.email = email.downcase }
	before_create :create_remember_token

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	# validates :username, presence: true, length: { minimum: 4 }, uniqueness: { case_sensitive: false }	
	validates :password, length: { minimum: 6 }

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private 
		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :signed_in_user
		
	def index
		@jobs = Job.paginate(page: params[:page])
	end

	def new
		@client = Client.new
		@client.locations.build
		@client.site_contacts.build
		@client.client_reps.build
		@job = @client.jobs.build
		@job.build_sale_order unless @job.sale_order
		@client.build_user unless @client.user


		@sale_order = SaleOrder.new

		@attach = Attach.new
		@attaches = @job.attaches
		@tech_job = TechJob.new
		@note = Note.new
	end

	def edit
		@job = Job.find(params[:id])
		@client = Client.find_by(id: @job.id)
		@attach = Attach.new
		@attaches = @job.attaches
		@tech_job = TechJob.new
		@note = Note.new
	end

	def create
		# @job = Job.new(job_params)
		# if @job.blank?
		# 	flash[:error] = 'No job exist'
		# 	render 'new'
		# end
	end

	def update
		@job = Job.find(params[:id])
		if @job.update(job_params)
			flash[:success] = "updated successfully"
			redirect_to edit_job_path(@job)
		else
			render 'edit'
		end
	end

	private
		def job_params
			params.require(:job).permit(
				:start_date,
				:end_date,
				:start_time,
				:end_time,
				:status,
				sale_order_attributes: [
					:id,
					:sales_order,
					:purchase_order,
					:item,
					:quantity,
					:price
				],
				attaches_attributes: [
					:id,
					:attach,
					:description,
					:admin_only
				]
			)
		end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/attaches_helper.rb
module AttachesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
    	user == current_user
  	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
	end

	def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end
end

app/helpers/teches_helper.rb
module TechesHelper
end

app/helpers/techs_helper.rb
module TechsHelper
end

app/views/jobs/_job.html.erb
<tr>
	<td><%= job.client.created_at.strftime("%m/%d/%Y") %></td>	
	<td><%= render job.client.site_contacts.first %></td>
	<td><%= job.client.city %></td>
	<td><%= job.client.name %></td>
	<td><%= render job.client.client_reps.first %></td>
	<td></td>
	<td></td>
	<td></td>
	<td><%= job.status %></td>
	<td>
		<%= link_to(edit_job_path(job)) do %>
			<i class="glyphicon glyphicon-pencil"></i>
		<% end %>
	</td>
</tr>

app/views/jobs/edit.html.erb
<ul class="nav nav-tabs" id="nav-tab" style="font-size: 16px;">
    <li class="job-tab active"><a href="#job" data-toggle="tab">JOB #: <%= @job.id %> </a></li>
    <li class="job-tab">
      <a href="#document" data-toggle="tab">DOCUMENTS
     
          <% @attaches.each do |attach| %>
            <% if attach.attach_type == 'Documents' %>
              [<%= @job.attaches.count %> items]
            <% end %>
          <% end %>
      </a>
    </li>
    <li class="job-tab"><a href="#image" data-toggle="tab">IMAGES [2 items]
      
    </a></li>
    <li class="job-tab"><a href="#signed" data-toggle="tab">SIGNED WORD TICKET [NONE]</a></li>
</ul>

<div class="tab-content tab-bg">
  <br>
  <div class="tab-pane active" id="job">
    
    <div class="row row-content" style="background-color: #27b999;">
      <div class="form-group col-xs-7" style="padding-left: 15px; padding-top: 20px; padding-bottom: 10px;">
          <label for="orginalPrice" class="control-label col-xs-2">Action</label>
          <div class="col-xs-8">
              <input type="text" class="form-control" id="orginalPrice">
          </div>
      </div>
    </div>
    
    <%= form_for(@client, class: 'form-horizontal') do |f| %>
      <%= render(partial: 'clients/client_field', locals: {f: f}) %>

      <%= f.fields_for :locations do |l| %>
        <%= render 'clients/location_field', f: l %>
      <% end %>

      <%= f.fields_for :site_contacts do |s| %>
        <%= render 'clients/site_contact_field', f: s %>
      <% end %>

      <%= f.fields_for :client_reps do |r| %>
        <%= render 'clients/client_rep_field', f: r %>
      <% end %>

      <div style="margin-left: 10px;"><%= f.submit "Add Contact", class: "btn lg-button" %></div>
    <% end %>  
    <br>
    
    <%= form_for(@job, class: 'form_horizontal') do |j| %>
      <%= j.fields_for :sale_order do |so| %>
        <%= render(partial: 'sale_orders/sale_order_field', locals: {j: so}) %>
      <% end %>
    <% end %>
    <br>
    <!-- attach form -->
    <%= form_for(@attach, :html => {:multipart => true}, class: 'form_horizontal') do |f| %>
      <%= render 'attaches/attach_field', f: f %>
      
    <% end %>
    
<div class="separetor"></div>
    <!-- Schedule form -->
    <%= form_for(@tech_job, class: 'form_horizontal') do |f| %>
      <%= render 'tech_jobs/tech_job_field', f: f %>
    <% end %>

    <div class="separetor"></div>

    <%= form_for(@note, class: 'form_horizontal') do |f| %>
      <%= render 'notes/note_field', f: f %>
    <% end %>
  </div>

  <div class="tab-pane" id="document">
    <table class="table">
      <tr>
        <th>NAME</th>
        <th>DESCRIPTION</th>
        <th>DOWNLOAD</th>
      </tr>
      <% @attaches.each do |attach| %>
        <% if attach.attach_type == 'Documents' %>
          <tr>
            <td><%= attach.document %></td>
            <td><%= attach.description %></td>
            <td>
              <%= link_to 'Download', attach.document_url %> | 
              <%= link_to 'Delete', attach, method: :delete, confirm: 'Are you sure that you want to delete #{attach.name}' %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>

  <div class="tab-pane" id="image">
    <table class="table">
      <tr>
        <th>NAME</th>
        <th>DESCRIPTION</th>
        <th>DOWNLOAD</th>
      </tr>
      <% @attaches.each do |attach| %>
        <% if attach.attach_type == 'Images' %>
          <tr>
            <td><%= attach.document %></td>
            <td><%= attach.description %></td>
            <td>
              <%= link_to 'Download', attach.document_url %> | 
              <%= link_to 'Delete', attach, method: :delete, confirm: 'Are you sure that you want to delete #{attach.name}' %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>
  <div class="tab-pane" id="signed">
    <table class="table">
      <tr>
        <th>NAME</th>
        <th>DESCRIPTION</th>
        <th>DOWNLOAD</th>
      </tr>
      <% @attaches.each do |attach| %>
        <% if attach.attach_type == 'Signed Work Ticket' %>
          <tr>
            <td><%= attach.document %></td>
            <td><%= attach.description %></td>
            <td>
              <%= link_to 'Download', attach.document_url %> | 
              <%= link_to 'Delete', attach, method: :delete, confirm: 'Are you sure that you want to delete #{attach.name}' %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="row row-content" style="padding-bottom: 7px;">
	<div class="pull-right">
		<%= link_to 'Add Job', new_job_path, class: 'btn lg-button' %>
	</div>
</div>
<div class="row lg-bg-white">
	<table class="table">
		<tr>
			<th>Date</th>
			<th>SITE</th>
			<th>CITY/STATE</th>
			<th>CLIENT</th>
			<th>REP</th>
			<th>CONTACT</th>
			<th>TECH</th>
			<th>SO #</th>
			<th>STATUS</th>
			<th>Add Job Details</th>
		</tr>
		<%= render @jobs %>
	</table>
</div>

app/views/jobs/new.html.erb
<ul class="nav nav-tabs" id="nav-tab" style="font-size: 20px;">
    <li class="job-tab active"><a href="#job" data-toggle="tab">JOB #: <p style="font-size: 15px;">&nbsp;</p></a></li>
    <li class="job-tab"><a href="#document" data-toggle="tab">DOCUMENTS<p style="font-size: 15px;">[NONE]</p></a></li>
    <li class="job-tab"><a href="#image" data-toggle="tab">IMAGES <p style="font-size: 15px;">[NONE]</p></a></li>
    <li class="job-tab"><a href="#signed" data-toggle="tab">SIGNED WORD TICKET <p style="font-size: 15px;">[NONE]</p></a></li>
</ul>

<div class="tab-content tab-bg">
  <br>
  <div class="tab-pane active" id="job">
    
    <div class="row row-content" style="background-color: #27b999;">
      <div class="form-group col-xs-7" style="padding-left: 15px; padding-top: 20px; padding-bottom: 10px;">
          <label for="orginalPrice" class="control-label col-xs-2">Action</label>
          <div class="col-xs-8">
              <input type="text" class="form-control" id="orginalPrice">
          </div>
      </div>
    </div>
    
   <%= form_for(@client, class: 'form-horizontal') do |f| %>
      <%= render(partial: 'clients/client_field', locals: {f: f}) %>

      <%= f.fields_for :user do |l| %>
        <%= l.hidden_field :client_id, value: @client.id %>
      <%= l.hidden_field :role, value: 'client' %>
        <%= render 'shared/user_field', f: l %>
      <% end %>

      <%= f.fields_for :locations do |l| %>
        <%= render 'clients/location_field', f: l %>
      <% end %>

      <%= f.fields_for :site_contacts do |s| %>
        <%= render 'clients/site_contact_field', f: s %>
      <% end %>

      <%= f.fields_for :client_reps do |r| %>
        <%= render 'clients/client_rep_field', f: r %>
      <% end %>

      <div style="margin-left: 10px;"><%= f.submit "Save", class: "btn lg-button" %></div>

      <%= f.fields_for :jobs do |j| %>
        <%= render 'clients/job_field', f: j %>
        <%= j.fields_for :sale_order do |so| %>
          <%= render(partial: 'sale_orders/sale_order_field', locals: {j: so}) %>
        <% end %>
      <% end %>
    <% end %> <br>


    <!-- Schedule form -->
    <%= form_for(@tech_job, class: 'form_horizontal') do |f| %>
      <%= render 'tech_jobs/tech_job_field', f: f %>
    <% end %>

    <div class="separetor"></div>

    <%= form_for(@note, class: 'form_horizontal') do |f| %>
      <%= render 'notes/note_field', f: f %>
    <% end %>
    
    <br>

    
    <div class="separetor"></div>
  </div>

  <div class="tab-pane" id="document">
    <h2>No job is created  </h2>
  </div>
  <div class="tab-pane" id="image">
    <h2>No job is created  </h2>
  </div>
  <div class="tab-pane" id="signed">
    <h2>No job is created  </h2>  
  </div>
</div>

app/views/jobs/show.html.erb
show