config/routes.rb
Selectcom::Application.routes.draw do
  # get "admins/new"
  # get "dashboard/index"

  root 'dashboard#index'
  resources :jobs
  resources :clients
  resources :sessions
  resources :teches
  resources :admins
  resources :sale_orders
  resources :attaches
  resources :tech_jobs
  resources :notes
  
  match '/signin',      to: 'sessions#new',           via: 'get'
  match '/signout',     to: 'sessions#destroy',       via: 'delete'
  match '/new_job',    to: 'jobs#new',               via: 'delete'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
	has_one :user

	accepts_nested_attributes_for :user
	
	has_attached_file :photo, style: { :medium => "400x300>", :thumb => "100x100>" }
	validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }
end

app/models/attach.rb
class Attach < ActiveRecord::Base
	belongs_to :job
	mount_uploader :document, DocumentUploader
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many 	:locations, :dependent => :destroy
	has_many 	:site_contacts, :dependent => :destroy
	has_many 	:client_reps, :dependent => :destroy
	has_many    :jobs, :dependent => :destroy
	has_one     :user, :dependent => :destroy

	accepts_nested_attributes_for :locations, :allow_destroy => true
	accepts_nested_attributes_for :site_contacts, :allow_destroy => true
	accepts_nested_attributes_for :client_reps, :allow_destroy => true
	accepts_nested_attributes_for :jobs, :allow_destroy => true
	accepts_nested_attributes_for :user, :allow_destroy => true

	validates :name, presence: true
	validates :phone, presence: true
end

app/models/client_rep.rb
class ClientRep < ActiveRecord::Base
	belongs_to :client
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :client
	has_one :sale_order
	has_many :attaches
	has_many :tech_jobs
	has_many :notes

	# validates :client_id, presence: true
	accepts_nested_attributes_for :sale_order
	accepts_nested_attributes_for :attaches
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :client
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
	belongs_to :job
end

app/models/sale_order.rb
class SaleOrder < ActiveRecord::Base
	belongs_to :job
	# before_save { self.sales_order = sales_order.downcase }
	validates :sales_order, presence: true, uniqueness: { case_sensitive: false }
	# validates :job_id, presence: true
	
end

app/models/site_contact.rb
class SiteContact < ActiveRecord::Base
	belongs_to :client
end

app/models/tech.rb
class Tech < ActiveRecord::Base
	has_one :user
	has_many :tech_jobs

	accepts_nested_attributes_for :user
	
	has_attached_file :photo, style: { :medium => "400x300>", :thumb => "100x100>" }
	# validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }

end

app/models/tech_job.rb
class TechJob < ActiveRecord::Base
	belongs_to :job
	belongs_to :tech

	validates_uniqueness_of :job_id, :scope => :tech_id, :message => "can only have one tech assigned"
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :client
	belongs_to :tech
	belongs_to :admin
	has_many   :notes
	
	has_secure_password

	before_save { self.email = email.downcase }
	before_create :create_remember_token

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	# validates :username, presence: true, length: { minimum: 4 }, uniqueness: { case_sensitive: false }	
	validates :password, length: { minimum: 6 }

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private 
		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

	# before_action :set_client, only: [:update]

	def index
		@clients = Client.paginate(page: params[:page])
	end


	def create
		@client = Client.new(client_params)
		if @client.save
			@job = Job.find_by(client_id: @client.id)
			flash[:success] = "Client added successfully"
			redirect_to edit_job_path(@job)
		else
			render 'jobs/new'
		end
	end

	# def edit
	# 	@job = Job.find_by(params[:id])
	# 	@client = @job.client
	# end

	def update
		@job = Job.find(params[:id])
		@client = @job.client
		if @client.update_attributes(client_params)
			flash[:success] = "Client updated successfully"
			redirect_to edit_job_path(@job)
		else
			render 'edit'
		end
	end

	private

		def client_params
			params.require(:client).permit(
				:name,
				:phone,
				:fax,
				:url,
				:address,
				:city,
				user_attributes: [
					:id,
					:email,
					:password,
					:password_confirmation,
					:role
				],
				locations_attributes: [
					:id,
					:site,
					:fax,
					:phone,
					:url,
					:address
				],
				site_contacts_attributes: [
					:id,
					:contact,
					:office,
					:cell,
					:email,
					:position
				],
				client_reps_attributes: [
					:id,
					:name,
					:contact,
					:office,
					:cell,
					:email,
					:position
				],
				jobs_attributes: [
					:id,
					:start_date,
					:end_date,
					:start_time,
					:end_time,
					:status,
					sale_order_attributes: [
						:id,
						:sales_order,
						:purchase_order,
						:item,
						:quantity,
						:price
					]
				]

			)
		end

		def update_client_params
			params.require(:client).permit(
				:name,
				:phone,
				:fax,
				:url,
				:address,
				:city,
				user_attributes: [
					:id,
					:email,
					:password,
					:password_confirmation,
					:role
				],
				locations_attributes: [
					:id,
					:site,
					:fax,
					:phone,
					:url,
					:address
				],
				site_contacts_attributes: [
					:id,
					:contact,
					:office,
					:cell,
					:email,
					:position
				],
				client_reps_attributes: [
					:id,
					:name,
					:contact,
					:office,
					:cell,
					:email,
					:position
				]
			)
		end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/attaches_helper.rb
module AttachesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
    	user == current_user
  	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
	end

	def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end
end

app/helpers/teches_helper.rb
module TechesHelper
end

app/helpers/techs_helper.rb
module TechsHelper
end

app/views/clients/_client.html.erb
<tr>
	<td><%= client.name %></td>
	<td><%= client.city %></td>
	<td>Main</td>
	<td><%= render client.locations %></td>
	<td><%= client.user.email %></td>

	<% client.jobs.each do |job| %>
		<% if job.status == 'open' %>
			<td><%= client.jobs.count %></td>		
		<% end %>
	<% end %>
	<td></td>
</tr>

app/views/clients/_client_field.html.erb
<%= render 'shared/error_messages', object: f.object %>
<div class="row" style="margin-left: 10px; margin-right: 10px;">
	<div class="pull-left" style="font-size: 24px; font-weight: 5px; padding-bottom: 10px;">Client</div>
</div>
<div class="separetor"></div><br>

<div id="client" class="row row-content">
	<div class='col-xs-6'>
		<div class='form-group'>
		    <%= f.label :name, 'Name', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :name, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :phone, 'Phone #', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :phone, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :fax, 'Fax #', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :fax, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :url, 'URL', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :url, class: 'form-control' %>
		    </div>
		</div><br>

	</div>

	<div class='col-xs-6'>
		<div class='form-group'>
		    <%= f.label :city, 'City', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :city, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :address, 'Address', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_area :address, rows: 8, cols: 100,  class: 'form-control' %>
		    </div>
		</div><br>
		
	</div>
</div>

app/views/clients/_client_rep_field.html.erb
<!-- Client Rep details -->
<div class="row" style="margin-left: 10px; margin-right: 10px;">
	<div class="pull-left" style="font-size: 24px; font-weight: 5px; padding-bottom: 10px;">CLIENT REP</div>
</div>
<div class="separetor"></div><br>

<%= f.hidden_field :client_id, value: @client.id %>

<div id="rep" class="row row-content">
	<div class='col-xs-6'>
		<div class='form-group'>
		    <%= f.label :name, 'Name', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :name, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :contact, 'Contact', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :contact, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :office, 'Office #', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :office, class: 'form-control' %>
		    </div>
		</div><br>

	</div>

	<div class='col-xs-6'>

		<div class='form-group'>
		    <%= f.label :cell, 'Cell #', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :cell, class: 'form-control' %>
		    </div>
		</div><br>
		
		<div class='form-group'>
		    <%= f.label :email, 'Email', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :email, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :position, 'Position', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :position, class: 'form-control' %>
		    </div>
		</div><br>
	</div>
</div>

app/views/clients/_job_field.html.erb
<%= f.hidden_field :client_id, value: @client.id %>
<%= f.hidden_field :status, value: 'open' %>

app/views/clients/_location_field.html.erb
<div class="row" style="margin-left: 10px; margin-right: 10px;">
	<div class="pull-left" style="font-size: 24px; font-weight: 5px; padding-bottom: 10px;">Location</div>
</div>
<div class="separetor"></div><br>

<%= f.hidden_field :client_id, value: @client.id %>

<div id="location" class="row row-content">
	<div class='col-xs-6'>
		<div class='form-group'>
		    <%= f.label :site, 'Site', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :site, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :fax, 'Fax #', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :fax, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :phone, 'Phone #', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :phone, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :url, 'URL', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :url, class: 'form-control' %>
		    </div>
		</div><br>
	</div>

	<div class='col-xs-6'>
		<div class='form-group'>
		    <%= f.label :address, 'Address', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_area :address, rows: 7, cols: 100,  class: 'form-control' %>
		    </div>
		</div>

		<div class='form-group'>
		    <%= f.label :address, 'Address', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= check_box("Save as master", "", {}, 1, 0)%>
		    </div>
		</div>
	</div>
</div>

app/views/clients/_site_contact_field.html.erb
<div class="row" style="margin-left: 10px; margin-right: 10px;">
	<div class="pull-left" style="font-size: 24px; font-weight: 5px; padding-bottom: 10px;">SITE CONTACT</div>
</div>

<div class="separetor"></div><br>

<%= f.hidden_field :client_id, value: @client.id %>

<div id="site" class="row row-content">
	<div class='col-xs-6'>
		<div class='form-group'>
		    <%= f.label :contact, 'Contact', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :contact, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :office, 'Office #', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :office, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :cell, 'Cell #', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :cell, class: 'form-control' %>
		    </div>
		</div><br>
	</div>

	<div class='col-xs-6'>
		<div class='form-group'>
		    <%= f.label :email, 'Email', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :email, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :position, 'Position', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :position, class: 'form-control' %>
		    </div>
		</div><br>
	</div>
</div>

app/views/clients/_update_client.html.erb
<%= render 'shared/error_messages', object: f.object %>
<div class="row" style="margin-left: 10px; margin-right: 10px;">
	<div class="pull-left" style="font-size: 24px; font-weight: 5px; padding-bottom: 10px;">Client</div>

	<div class="pull-right">
		<div style="margin-left: 10px;"><%= f.submit "Update Client", class: "btn lg-button" %></div>
	</div>
</div>
<div class="separetor"></div><br>

<div id="client" class="row row-content">
	<div class='col-xs-6'>
		<div class='form-group'>
		    <%= f.label :name, 'Name', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :name, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :phone, 'Phone #', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :phone, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :fax, 'Fax #', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :fax, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :url, 'URL', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :url, class: 'form-control' %>
		    </div>
		</div><br>
	</div>

	<div class='col-xs-6'>
		<div class='form-group'>
		    <%= f.label :address, 'Address', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_area :address, rows: 7, cols: 100,  class: 'form-control' %>
		    </div>
		</div>
		<div class='form-group'>
		    <%= f.label :city, 'City', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :city, class: 'form-control' %>
		    </div>
		</div><br>
	</div>
</div>

app/views/clients/_update_location.html.erb
<div class="row" style="margin-left: 10px; margin-right: 10px;">
	<div class="pull-left" style="font-size: 24px; font-weight: 5px; padding-bottom: 10px;">Location</div>

	<div class="pull-right">
		<div style="margin-left: 10px;"><%= f.submit "Update Client", class: "btn lg-button" %></div>
	</div>
</div>
<div class="separetor"></div><br>

<%= f.hidden_field :client_id, value: @client.id %>

<div id="location" class="row row-content">
	<div class='col-xs-6'>
		<div class='form-group'>
		    <%= f.label :site, 'Site', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :site, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :fax, 'Fax #', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :fax, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :phone, 'Phone #', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :phone, class: 'form-control' %>
		    </div>
		</div><br>

		<div class='form-group'>
		    <%= f.label :url, 'URL', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_field :url, class: 'form-control' %>
		    </div>
		</div><br>
	</div>

	<div class='col-xs-6'>
		<div class='form-group'>
		    <%= f.label :address, 'Address', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= f.text_area :address, rows: 7, cols: 100,  class: 'form-control' %>
		    </div>
		</div>

		<div class='form-group'>
		    <%= f.label :address, 'Address', class: 'control-label col-xs-3' %>
		    <div class="col-xs-8">
		    	<%= check_box("Save as master", "", {}, 1, 0)%>
		    </div>
		</div>
	</div>
</div>

app/views/clients/index.html.erb
<div class="row row-content" style="padding-bottom: 7px;">
	<div class="pull-right">
		<%= link_to 'Add Client', new_client_path, class: 'btn lg-button' %>
	</div>
</div>
<div class="row lg-bg-white">
	<table class="table">
		<tr>
			<th>CLIENT</th>
			<th>CITY/STATE</th>
			<th>MAIN</th>
			<th>CONTACT</th>
			<th>EMAIL</th>
			<th>OPEN JOBS</th>
			<th>RECEIVABLES</th>
		</tr>
		<%= render @clients %>
	</table>


</div>

app/views/clients/new.html.erb
<div class="row lg-bg-white">
	<%= form_for(@client, class: 'form-horizontal') do |f| %>
	  <%= render(partial: 'client_field', locals: {f: f}) %>

	  <%= f.fields_for :user do |l| %>
	  	<%= l.hidden_field :client_id, value: @client.id %>
		<%= l.hidden_field :role, value: 'client' %>
	  	<%= render 'shared/user_field', f: l %>
	  <% end %>

	  <%= f.fields_for :locations do |l| %>
	  	<%= render 'location_field', f: l %>
	  <% end %>

	  <%= f.fields_for :site_contacts do |s| %>
	  	<%= render 'site_contact_field', f: s %>
	  <% end %>

	  <%= f.fields_for :client_reps do |r| %>
	  	<%= render 'client_rep_field', f: r %>
	  <% end %>

	  <%= f.fields_for :jobs do |j| %>
	  	<%= render 'job_field', f: j %>
	  <% end %>

	  <div style="margin-left: 10px;"><%= f.submit "Save", class: "btn lg-button" %></div>
	<% end %> 	
	<br>
</div>